kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx
spec:
  accessModes:
    - ReadWriteOnce
#  volumeMode: Block
  resources:
    requests:
      storage: 10Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      runtimeClassName: kata-clh
      containers:
        - name: myfrontend
          image: nginx
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: "/var/www/html"
              name: mypd
#          volumeDevices:
#            - devicePath: /dev/block
#              name: mypd
      volumes:
        - name: mypd
          persistentVolumeClaim:
            claimName: nginx