apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: stress
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: stress
    spec:
      runtimeClassName: kata-clh
      containers:
        - name: cpu0
          image: vish/stress
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
          args:
            - "-cpus"
            - "20"
            - "-mem-total"
            - "1Gi"
            - "-mem-alloc-sleep"
            - "1m"
